In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [2]:
iris= load_iris()

In [3]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [4]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [5]:
df = pd.DataFrame(np.c_[iris['data'], iris['target']], columns = np.append(iris['feature_names'], ['target']))

In [6]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [7]:
df = df.sample(frac =1)  
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
7                 5.0               3.4                1.5               0.2   
40                5.0               3.5                1.3               0.3   
72                6.3               2.5                4.9               1.5   
22                4.6               3.6                1.0               0.2   
46                5.1               3.8                1.6               0.2   

    target  
7      0.0  
40     0.0  
72     1.0  
22     0.0  
46     0.0

In [8]:
x = df.iloc[:, 0:4].values
y = df.iloc[:, 4].values

In [9]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, train_size = 0.75)

In [10]:
from sklearn.naive_bayes import GaussianNB 
model = GaussianNB()
model.fit(xtrain, ytrain)

GaussianNB()

In [11]:
ypred = model.predict(xtest)
ypred

array([1., 2., 1., 2., 1., 2., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0.,
       0., 1., 1., 1., 1., 1., 0., 0., 0., 2., 0., 0., 1., 2., 0., 2., 2.,
       2., 1., 2., 2.])

In [12]:
ytest

array([1., 2., 1., 2., 1., 2., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0.,
       0., 1., 1., 1., 1., 1., 0., 0., 0., 2., 0., 0., 1., 2., 0., 2., 2.,
       1., 1., 2., 2.])

In [13]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [14]:
accuracy_score(ytest, ypred)

0.9736842105263158

In [15]:
cm = confusion_matrix(ytest, ypred)
cm

array([[ 9,  0,  0],
       [ 0, 13,  2],
       [ 0,  0, 14]], dtype=int64)